### ISSUE TITLE
Please fix test "queryPatientsNullInOrder"

### ISSUE THREAD

**Issue by MichaelSp** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#154]
I've disabled this test https://github.com/ImisDevelopers/1_011_a_infektionsfall_uebermittellung/blob/1d8327bf6c7aa1ae2682eba57a41f2b3193bbc9b/server/src/test/java/de/coronavirus/imis/services/PatientServiceTest.java#L13
because it fails and I don't know how to fix it.

**Comment by jojo19893** [comment]
I think the entire test has no assertions....

**Comment by MichaelSp** [comment]
It fails to run even without assertions :D

**Comment by jewelt** [comment]
Oh sorry. Let me fix this.

**Comment by jewelt** [comment]
The test was correct. No exception should be thrown in the method if the parameters are null. The problem was that the build.gradle was not correct. I've fixed the service and the build.gralde. Please check it in your local env. I've opened a PR. https://github.com/ImisDevelopers/1_011_a_infektionsfall_uebermittellung/pull/160
