### ISSUE TITLE
Erweiterung Kontaktperson

### ISSUE THREAD

**Issue by btobi** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#301]
- Zu jeder Person kann eine Kontaktperson hinzugefügt werden. Hier werden nur persönliche Daten und Informationen für den Kontakt abgefragt: Name, Vorname, Geb., Geschlecht, Adresse, Telefon, E-Mail, Derzeitiger Aufenthaltsort, weitere sinnvolle pers. Daten, Art des Kontakts (Haushaltskontakt, beruflicher Kontakt, Kontakt in Gemeinschaftseinrichtung, sonstiger Kontakt), Datum des Kontakts, Beschreibung aka Freitext)

- Kontaktort als Freitextfeld

**Description from #255** 

Patient registration: within section 'Exposition' add a possibility to enter 'Quelle der Infektion (falls bekannt)' with the following 3 fields:
 1. a possibility to seach for an existing patient based on name etc (regular patient identify) andstore the reference to that patient if selected ... labeled as 'bekannter Kontakt'
 2. a possibility to enter any person information, location information or event information as string ... labeled as 'Daten zur Infektionsquelle'
 3. a date of exposition labeled as 'Letztes Kontakt-Datum'

Hint: Index patient information should not appear in self registration.

Further description #266 #265

**Comment by t0bska** [comment]
No idea, if this is the right issue for this, but:

In "Patientendetails -> Infektionskette -> Kontaktpersonen -> Hinzufügen" it would be extremely nice if the user had the option to "Neu erfassen" instead of only being able to choose existing Patients. (This could then lead to the register patient-Form with preselected "Quelle der Infektion")

_Furthermore there should be an Option to view a person's details before selecting it, but that's not that important for now._

**Comment by Jochen-Sch** [comment]
@t0bska The described changes exactly refer to the aspect to capture a new person which does not yet exist in the system. Upon saving the according fields like Name ZIP code, City will be used to create a new patient record that can later be completed as investigation in the health agency has collected all necessary data

**Comment by JonasCir** [comment]
@btobi @t0bska @Jochen-Sch Verify and close

**Comment by JonasCir** [comment]
@lordpomeroy
