### ISSUE TITLE
Cloud SQL database not initialized

### ISSUE THREAD

**Issue by lordpomeroy** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#77]
Add init script to deployment or allow backend to create tables if not existing.

**Comment by MichaelSp** [comment]
Found this in the logs
`org.postgresql.util.PSQLException: ERROR: relation "patient" does not exist` 
and 
`java.io.FileNotFoundException: class path resource [sample_data/persons/person0.json] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/app.jar!/BOOT-INF/classes!/sample_data/persons/person0.json` 
But DB should be fine...
checking db content

**Comment by MichaelSp** [comment]
ok, schema is empty

**Comment by MichaelSp** [comment]
Would this be sufficient
```
 jpa:
    hibernate:
      ddl-auto: create
```
I'm not a spring/hibernate expert, not sure if this is a good idea in production?

**Comment by MichaelSp** [comment]
I've defined `ddl-auto:create` once to create the DB with current scheme.

Can you pls check? PR would be obsolete then.

**Comment by lordpomeroy** [comment]
Looks good.
